[tool.poetry]
name = "miniprojekti"
version = "0.1.0"
description = "Ohtu miniprojekti"
authors = ["Mich-FI <mikaelgaram@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
